repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-ast
        language_version: python3.6
    -   id: check-builtin-literals
        language_version: python3.6
    -   id: check-docstring-first
        language_version: python3.6
    -   id: check-json
        language_version: python3.6
    -   id: check-merge-conflict
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: detect-private-key
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
        types: [python]
    -   id: flake8
        language_version: python3.6
        args:
        - --max-line-length=160
        - --ignore=E252,F401,W503
    -   id: requirements-txt-fixer
        language_version: python3.6
    -   id: trailing-whitespace
        language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
        language_version: python3.6
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.2
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
        args: [--py3-plus]
