FROM python:3.6.7-slim

LABEL maintainer="jparkie <https://github.com/jparkie>"
LABEL description="A Docker image used for building cookiecutter-python-swagger projects"

# Install Project Dependencies:
RUN pip install tox tox-venv

WORKDIR /repository

# Expose 8080 for HTTP:
EXPOSE 8080
