pipeline {
	agent none
	stages {
		stage('Checkout') {
			agent any
			steps {
				checkout scm
			}
		}
		stage('Clean') {
			agent {
				dockerfile {
					filename 'Dockerfile.develop'
				}
			}
			steps {
				sh 'make clean'
			}
		}
		stage('Unit Test') {
			agent {
				dockerfile {
					filename 'Dockerfile.develop'
				}
			}
			steps {
				sh 'make test'
			}
		}
	}
}
